/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     * @param pName {String} 
     * @param pdate1 {Date} 
     * @param pdate2 {Date} 
     * @param pdate3 {Date} 
     */
    constructor(pName, pdate1, pdate2, pdate3) { 
        
        Project.initialize(this, pName, pdate1, pdate2, pdate3);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pName, pdate1, pdate2, pdate3) { 
        obj['pName'] = pName;
        obj['pdate1'] = pdate1;
        obj['pdate2'] = pdate2;
        obj['pdate3'] = pdate3;
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('pName')) {
                obj['pName'] = ApiClient.convertToType(data['pName'], 'String');
            }
            if (data.hasOwnProperty('pdate1')) {
                obj['pdate1'] = ApiClient.convertToType(data['pdate1'], 'Date');
            }
            if (data.hasOwnProperty('pdate2')) {
                obj['pdate2'] = ApiClient.convertToType(data['pdate2'], 'Date');
            }
            if (data.hasOwnProperty('pdate3')) {
                obj['pdate3'] = ApiClient.convertToType(data['pdate3'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Project.prototype['_id'] = undefined;

/**
 * @member {String} pName
 */
Project.prototype['pName'] = undefined;

/**
 * @member {Date} pdate1
 */
Project.prototype['pdate1'] = undefined;

/**
 * @member {Date} pdate2
 */
Project.prototype['pdate2'] = undefined;

/**
 * @member {Date} pdate3
 */
Project.prototype['pdate3'] = undefined;






export default Project;

